CREATE TABLE `users` (
  `id`            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `username`      TEXT    NOT NULL                           UNIQUE DEFAULT "",
  `hash_password` TEXT    NOT NULL                                  DEFAULT "",
  `hash_email`    TEXT    NOT NULL                                  DEFAULT ""
);

CREATE TABLE `tables` (
  `id`             INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `owner`          TEXT    NOT NULL                                  DEFAULT "",
  `name`           TEXT    NOT NULL                                  DEFAULT "",
  `published`      INTEGER NOT NULL                                  DEFAULT 0,
  `passcode`       TEXT                                              DEFAULT "",
  `maxPlayers`     INTEGER                                           DEFAULT 4,
  `players`        TEXT                                              DEFAULT "",
  `charactersIDs`  TEXT                                              DEFAULT "",
  `charactersData` TEXT                                              DEFAULT "",
  `monstersIDs`    TEXT                                              DEFAULT "",
  `monstersData`   TEXT                                              DEFAULT ""
);

CREATE TABLE `messages` (
  `id`         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `tableID`    INTEGER NOT NULL                                  DEFAULT 0,
  `username`   INTEGER NOT NULL                                  DEFAULT "",
  `senderID`   INTEGER                                           DEFAULT 0,
  `senderName` TEXT                                              DEFAULT "",
  `type`       TEXT                                              DEFAULT "",
  `text`       TEXT                                              DEFAULT "",
  `action`     TEXT                                              DEFAULT ""
);

CREATE TABLE `characters` (
  `id`                           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `owner`                        TEXT    NOT NULL                                  DEFAULT "",
  `name`                         TEXT    NOT NULL                                  DEFAULT "Character Name",
  `image`                        TEXT                                              DEFAULT "",
  `level`                        INTEGER                                           DEFAULT 1,
  `proficiencyBonus`             INTEGER                                           DEFAULT 0,
  `xp`                           INTEGER                                           DEFAULT 0,
  `xpNextLevel`                  INTEGER                                           DEFAULT 0,
  `class`                        TEXT                                              DEFAULT "barbarian-pre",
  `race`                         TEXT                                              DEFAULT "Hill Dwarf",
  `size`                         TEXT                                              DEFAULT "Small",
  `alignment`                    TEXT                                              DEFAULT "Unaligned",
  `characterInfo`                TEXT                                              DEFAULT "Religion: ...\n\nGender: ...\nAge: ...\n\nHeight: ...\nWeight: ...\nEyes: ...\nHair: ...\n\nBackground: ...\n\nPersonality Traits: ...\n\nIdeals: ...\n\nFlaws: ...\n\nBonds: ...\n\nNotes: ...\n\n",
  `strengthScore`                INTEGER                                           DEFAULT 8,
  `dexterityScore`               INTEGER                                           DEFAULT 8,
  `constitutionScore`            INTEGER                                           DEFAULT 8,
  `intelligenceScore`            INTEGER                                           DEFAULT 8,
  `wisdomScore`                  INTEGER                                           DEFAULT 8,
  `charismaScore`                INTEGER                                           DEFAULT 8,
  `strengthModifier`             INTEGER                                           DEFAULT 0,
  `dexterityModifier`            INTEGER                                           DEFAULT 0,
  `constitutionModifier`         INTEGER                                           DEFAULT 0,
  `intelligenceModifier`         INTEGER                                           DEFAULT 0,
  `wisdomModifier`               INTEGER                                           DEFAULT 0,
  `charismaModifier`             INTEGER                                           DEFAULT 0,
  `passivePerception`            INTEGER                                           DEFAULT 0,
  `initiativeBonus`              INTEGER                                           DEFAULT 0,
  `savingThrowList`              TEXT                                              DEFAULT "",
  `savingThrowStrengthBonus`     INTEGER                                           DEFAULT 0,
  `savingThrowDexterityBonus`    INTEGER                                           DEFAULT 0,
  `savingThrowConstitutionBonus` INTEGER                                           DEFAULT 0,
  `savingThrowIntelligenceBonus` INTEGER                                           DEFAULT 0,
  `savingThrowWisdomBonus`       INTEGER                                           DEFAULT 0,
  `savingThrowCharismaBonus`     INTEGER                                           DEFAULT 0,
  `spellSaveDC`                  INTEGER                                           DEFAULT 0,
  `spellAttackModifier`          INTEGER                                           DEFAULT 0,
  `skillList`                    TEXT                                              DEFAULT "skillAthleticsNone;skillAcrobaticsNone;skillSleightOfHandNone;skillStealthNone;skillArcanaNone;skillHistoryNone;skillInvestigationNone;skillNatureNone;skillReligionNone;skillAnimalHandlingNone;skillInsightNone;skillMedicineNone;skillPerceptionNone;skillSurvivalNone;skillDeceptionNone;skillIntimidationNone;skillPerformanceNone;skillPersuasionNone",
  `skillAthleticsModifier`       INTEGER                                           DEFAULT 0,
  `skillAcrobaticsModifier`      INTEGER                                           DEFAULT 0,
  `skillSleightOfHandModifier`   INTEGER                                           DEFAULT 0,
  `skillStealthModifier`         INTEGER                                           DEFAULT 0,
  `skillArcanaModifier`          INTEGER                                           DEFAULT 0,
  `skillHistoryModifier`         INTEGER                                           DEFAULT 0,
  `skillInvestigationModifier`   INTEGER                                           DEFAULT 0,
  `skillNatureModifier`          INTEGER                                           DEFAULT 0,
  `skillReligionModifier`        INTEGER                                           DEFAULT 0,
  `skillAnimalHandlingModifier`  INTEGER                                           DEFAULT 0,
  `skillInsightModifier`         INTEGER                                           DEFAULT 0,
  `skillMedicineModifier`        INTEGER                                           DEFAULT 0,
  `skillPerceptionModifier`      INTEGER                                           DEFAULT 0,
  `skillSurvivalModifier`        INTEGER                                           DEFAULT 0,
  `skillDeceptionModifier`       INTEGER                                           DEFAULT 0,
  `skillIntimidationModifier`    INTEGER                                           DEFAULT 0,
  `skillPerformanceModifier`     INTEGER                                           DEFAULT 0,
  `skillPersuasionModifier`      INTEGER                                           DEFAULT 0,
  `weaponProficiencyList`        TEXT                                              DEFAULT "",
  `armorProficiencyList`         TEXT                                              DEFAULT "",
  `toolProficiencyList`          TEXT                                              DEFAULT "",
  `languageProficiencyList`      TEXT                                              DEFAULT "",
  `itemList`                     TEXT                                              DEFAULT "",
  `equippedWeaponList`           TEXT                                              DEFAULT "",
  `equippedArmor`                TEXT                                              DEFAULT "",
  `equippedShield`               TEXT                                              DEFAULT "",
  `equippedAccessoryList`        TEXT                                              DEFAULT "",
  `acValue`                      INTEGER                                           DEFAULT 1,
  `acValueMelee`                 INTEGER                                           DEFAULT 0,
  `acValueRanged`                INTEGER                                           DEFAULT 0,
  `acValueSpells`                INTEGER                                           DEFAULT 0,
  `hpMax`                        INTEGER                                           DEFAULT 1,
  `speed`                        INTEGER                                           DEFAULT 0,
  `coinCopper`                   INTEGER                                           DEFAULT 0,
  `coinSilver`                   INTEGER                                           DEFAULT 0,
  `coinElectrum`                 INTEGER                                           DEFAULT 0,
  `coinGold`                     INTEGER                                           DEFAULT 0,
  `coinPlatinum`                 INTEGER                                           DEFAULT 0,
  `actionList`                   TEXT                                              DEFAULT "",
  `notes`                        TEXT                                              DEFAULT ""
);

CREATE TABLE `monsters` (
  `id`                           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `owner`                        TEXT    NOT NULL                                  DEFAULT "",
  `name`                         TEXT    NOT NULL                                  DEFAULT "Monster Name",
  `image`                        TEXT                                              DEFAULT "",
  `size`                         TEXT                                              DEFAULT "Tiny",
  `creatureTypeList`             TEXT                                              DEFAULT "Aberration",
  `alignment`                    TEXT                                              DEFAULT "Unaligned",
  `challengeRating`              REAL                                              DEFAULT 0,
  `proficiencyBonus`             INTEGER                                           DEFAULT 0,
  `xpReward`                     INTEGER                                           DEFAULT 0,
  `hpMax`                        INTEGER                                           DEFAULT 1,
  `acValue`                      INTEGER                                           DEFAULT 1,
  `acType`                       TEXT                                              DEFAULT "naturalArmor",
  `acShield`                     INTEGER                                           DEFAULT 0,
  `speedList`                    TEXT                                              DEFAULT "speedWalking",
  `speedWalking`                 INTEGER                                           DEFAULT 0,
  `speedBurrowing`               INTEGER                                           DEFAULT 0,
  `speedClimbing`                INTEGER                                           DEFAULT 0,
  `speedFlying`                  INTEGER                                           DEFAULT 0,
  `speedSwimming`                INTEGER                                           DEFAULT 0,
  `strengthScore`                INTEGER                                           DEFAULT 8,
  `dexterityScore`               INTEGER                                           DEFAULT 8,
  `constitutionScore`            INTEGER                                           DEFAULT 8,
  `intelligenceScore`            INTEGER                                           DEFAULT 8,
  `wisdomScore`                  INTEGER                                           DEFAULT 8,
  `charismaScore`                INTEGER                                           DEFAULT 8,
  `strengthModifier`             INTEGER                                           DEFAULT 0,
  `dexterityModifier`            INTEGER                                           DEFAULT 0,
  `constitutionModifier`         INTEGER                                           DEFAULT 0,
  `intelligenceModifier`         INTEGER                                           DEFAULT 0,
  `wisdomModifier`               INTEGER                                           DEFAULT 0,
  `charismaModifier`             INTEGER                                           DEFAULT 0,
  `passivePerception`            INTEGER                                           DEFAULT 0,
  `initiativeBonus`              INTEGER                                           DEFAULT 0,
  `savingThrowList`              TEXT                                              DEFAULT "",
  `savingThrowStrengthBonus`     INTEGER                                           DEFAULT 0,
  `savingThrowDexterityBonus`    INTEGER                                           DEFAULT 0,
  `savingThrowConstitutionBonus` INTEGER                                           DEFAULT 0,
  `savingThrowIntelligenceBonus` INTEGER                                           DEFAULT 0,
  `savingThrowWisdomBonus`       INTEGER                                           DEFAULT 0,
  `savingThrowCharismaBonus`     INTEGER                                           DEFAULT 0,
  `skillList`                    TEXT                                              DEFAULT "skillAthleticsNone;skillAcrobaticsNone;skillSleightOfHandNone;skillStealthNone;skillArcanaNone;skillHistoryNone;skillInvestigationNone;skillNatureNone;skillReligionNone;skillAnimalHandlingNone;skillInsightNone;skillMedicineNone;skillPerceptionNone;skillSurvivalNone;skillDeceptionNone;skillIntimidationNone;skillPerformanceNone;skillPersuasionNone",
  `skillAthleticsModifier`       INTEGER                                           DEFAULT 0,
  `skillAcrobaticsModifier`      INTEGER                                           DEFAULT 0,
  `skillSleightOfHandModifier`   INTEGER                                           DEFAULT 0,
  `skillStealthModifier`         INTEGER                                           DEFAULT 0,
  `skillArcanaModifier`          INTEGER                                           DEFAULT 0,
  `skillHistoryModifier`         INTEGER                                           DEFAULT 0,
  `skillInvestigationModifier`   INTEGER                                           DEFAULT 0,
  `skillNatureModifier`          INTEGER                                           DEFAULT 0,
  `skillReligionModifier`        INTEGER                                           DEFAULT 0,
  `skillAnimalHandlingModifier`  INTEGER                                           DEFAULT 0,
  `skillInsightModifier`         INTEGER                                           DEFAULT 0,
  `skillMedicineModifier`        INTEGER                                           DEFAULT 0,
  `skillPerceptionModifier`      INTEGER                                           DEFAULT 0,
  `skillSurvivalModifier`        INTEGER                                           DEFAULT 0,
  `skillDeceptionModifier`       INTEGER                                           DEFAULT 0,
  `skillIntimidationModifier`    INTEGER                                           DEFAULT 0,
  `skillPerformanceModifier`     INTEGER                                           DEFAULT 0,
  `skillPersuasionModifier`      INTEGER                                           DEFAULT 0,
  `vulnerabilityList`            TEXT                                              DEFAULT "",
  `resistanceList`               TEXT                                              DEFAULT "",
  `immunityList`                 TEXT                                              DEFAULT "",
  `senseList`                    TEXT                                              DEFAULT "",
  `senseBlindsight`              INTEGER                                           DEFAULT 0,
  `senseDarkvision`              INTEGER                                           DEFAULT 0,
  `senseTremorsense`             INTEGER                                           DEFAULT 0,
  `senseTruesight`               INTEGER                                           DEFAULT 0,
  `languageProficiencyList`      TEXT                                              DEFAULT "",
  `specialTraitList`             TEXT                                              DEFAULT "",
  `actionList`                   TEXT                                              DEFAULT ""
);